# Form implementation generated from reading ui file 'lang_source.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 300))
        Form.setMaximumSize(QtCore.QSize(500, 300))
        self.ru_button = QtWidgets.QPushButton(Form)
        self.ru_button.setGeometry(QtCore.QRect(10, 50, 90, 200))
        self.ru_button.setStyleSheet("background-color: rgb(228, 227, 239);")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ru_button.sizePolicy().hasHeightForWidth())
        self.ru_button.setSizePolicy(sizePolicy)
        self.ru_button.setMinimumSize(QtCore.QSize(90, 200))
        self.ru_button.setMaximumSize(QtCore.QSize(90, 200))
        self.ru_button.setObjectName("ru_button")
        self.eng_button = QtWidgets.QPushButton(Form)
        self.eng_button.setGeometry(QtCore.QRect(140, 50, 90, 200))
        self.eng_button.setStyleSheet("background-color: rgb(228, 227, 239);")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eng_button.sizePolicy().hasHeightForWidth())
        self.eng_button.setSizePolicy(sizePolicy)
        self.eng_button.setMinimumSize(QtCore.QSize(90, 200))
        self.eng_button.setMaximumSize(QtCore.QSize(90, 200))
        self.eng_button.setObjectName("eng_button")
        self.file_button = QtWidgets.QPushButton(Form)
        self.file_button.setGeometry(QtCore.QRect(270, 50, 90, 200))
        self.file_button.setStyleSheet("background-color: rgb(228, 227, 239);")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_button.sizePolicy().hasHeightForWidth())
        self.file_button.setSizePolicy(sizePolicy)
        self.file_button.setMinimumSize(QtCore.QSize(90, 200))
        self.file_button.setMaximumSize(QtCore.QSize(90, 200))
        self.file_button.setObjectName("file_button")
        self.record_button = QtWidgets.QPushButton(Form)
        self.record_button.setGeometry(QtCore.QRect(400, 50, 90, 200))
        self.record_button.setStyleSheet("background-color: rgb(228, 227, 239);")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_button.sizePolicy().hasHeightForWidth())
        self.record_button.setSizePolicy(sizePolicy)
        self.record_button.setMinimumSize(QtCore.QSize(90, 200))
        self.record_button.setMaximumSize(QtCore.QSize(90, 200))
        self.record_button.setObjectName("record_button")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(240, 10, 20, 291))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 20, 101, 20))
        self.label.setStyleSheet("color: white;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 67, 17))
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(100, 140, 41, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(10, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(360, 140, 41, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.step = QtWidgets.QPushButton(Form)
        self.step.setGeometry(QtCore.QRect(400, 270, 89, 25))
        self.step.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.step.setObjectName("step")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ru_button.setText(_translate("Form", "RU"))
        self.eng_button.setText(_translate("Form", "ENG"))
        self.file_button.setText(_translate("Form", "select\nfile"))
        self.record_button.setText(_translate("Form", "record"))
        self.label.setText(_translate("Form", "LANGUAGE"))
        self.label_2.setText(_translate("Form", "SOURCE"))
        self.step.setText(_translate("Form", "continue"))